salas/reservaciones/urls.py
from django.conf.urls import url

from reservaciones.views import ReservaEmpleadoView, ReservaCreateView

urlpatterns = [
    url(r'^reserva$', ReservaEmpleadoView.as_view(), name='reserva'),
    url(r'^reserva/crear$', ReservaCreateView.as_view(), name='crearReserva'),

]

salas/sala_reuniones/urls.py
from django.conf.urls import url

from sala_reuniones.views import SalasListView, SalasDetailView, SalasCreateView,\
    SalasUpdateView, SalasDeleteView

urlpatterns = [
    url(r'^$', SalasListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', SalasDetailView.as_view(), name='detail'),
    url(r'^nuevo$', SalasCreateView.as_view(), name='new'),
    url(r'^editar/(?P<pk>\d+)$', SalasUpdateView.as_view(), name='edit'),
    url(r'^borrar/(?P<pk>\d+)$', SalasDeleteView.as_view(), name='delete'),
]

salas/salas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^reservaciones/', include('reservaciones.urls', namespace='reservaciones')),
]

admin.site.site_header = 'Administracion de HCMFront'

salas/reservaciones/models.py
from __future__ import unicode_literals

from django.conf.global_settings import AUTH_USER_MODEL
from django.db import models
from django.db.models.fields.related import ForeignKey

from sala_reuniones.models import Sala


ESTATUS_RESERVACION = (
    (1, 'No Disponible'),
    (2, 'Disponible'),
    (3, 'Reservada'),
    (4, 'Confirmada'),
)

class Reservacion(models.Model):
    """
    Modelo de reservacion
    """
    sala = ForeignKey(Sala, on_delete=models.PROTECT)
    user = ForeignKey(AUTH_USER_MODEL, on_delete=models.PROTECT)
    fecha = models.DateField('Fecha de reservacion')
    hora_inicio = models.TimeField('Hora inicio')
    hora_termino = models.TimeField('Hora termino')
    cantidad_personas = models.IntegerField('Cantidad de personas')
    estatus = models.IntegerField('Estatus', help_text='indica el estatus de la sala', choices=ESTATUS_RESERVACION)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = 'Reservacion'
        verbose_name_plural = 'Reservaciones'


class Insumo(models.Model):
    """
    Modelo de insumos
    """
    nombre = models.TextField('Nombre', max_length=30, help_text='indica el nombre del insumo')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Insumo'
        verbose_name_plural = 'Insumos'


class InsumoReservacion(models.Model):
    """
    Modelo que indica los insumos solicitados en la reservacion
    """
    insumo = ForeignKey(Insumo, on_delete=models.CASCADE, verbose_name='Insumo')
    reservacion = ForeignKey(Reservacion, on_delete=models.CASCADE, verbose_name='Reservacion')

    class Meta:
        verbose_name = 'Insumo de Reservacion'
        verbose_name_plural = 'Insumo de Reservaciones'


class InsumoSala(models.Model):
    """
    Modelo que indica los insumos que se pueden alquilar en la sala
    """
    insumo = ForeignKey(Insumo, on_delete=models.CASCADE, verbose_name='Insumo')
    sala = ForeignKey(Sala, on_delete=models.CASCADE, verbose_name='Sala')

    def __str__(self):
        return self.insumo.nombre

    class Meta:
        verbose_name = 'Insumo de Sala'
        verbose_name_plural = 'Insumo de Salas'

salas/sala_reuniones/models.py
from __future__ import unicode_literals
from django.db import models


class Sala(models.Model):
    """
    Modelo de sala
    """
    nombre = models.TextField('Nombre', max_length=30, help_text='indica el nombre de la sala')
    ubicacion = models.TextField('Ubicacion', max_length=30, help_text='indica la ubicacion de la sala')
    capacidad = models.IntegerField('Capacidad', help_text='indica  la capacidad en numero de personas de la sala')
    horario_disponibilidad = models.TimeField('Horario de Disponibilidad', help_text='indica la hora disponible')

    def __str__(self):
        return self.nombre

    def get_horario_disponibilidad(self):
        return self.horario_disponibilidad.strptime('%H:%M:%S')

    class Meta:
        verbose_name = 'Sala'
        verbose_name_plural = 'Salas'

salas/reservaciones/forms.py
from django import forms
from reservaciones.models import Insumo


class ReservaEmpleadoForm(forms.Form):
    cantidad_personas = forms.IntegerField()
    insumos = forms.ModelMultipleChoiceField(queryset=Insumo.objects.all())


    def validated_data(self):
        return self.data

salas/reservaciones/views.py
from datetime import datetime, timedelta
from django.shortcuts import render
from django.views.generic.edit import CreateView, FormView

from reservaciones.forms import ReservaEmpleadoForm
from reservaciones.models import Sala, Reservacion, Insumo, InsumoSala, InsumoReservacion




class ReservaEmpleadoView(FormView):
    form_class = ReservaEmpleadoForm
    success_url = 'reservaciones/salas_disponibles.html'
    template_name = 'reservaciones/reserva.html'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            cantidad = form.validated_data()['cantidad_personas']
            insumos = form.validated_data()['insumos']

            salas = Sala.objects.filter(capacidad__gte=cantidad, insumosala__insumo__in=insumos).exclude(
                id__in=Reservacion.objects.filter(estatus__in=(2, 3)).values_list('sala_id', flat=True)
            )

            arreglo_salas = []

            for sala in salas:
                ins = InsumoSala.objects.filter(sala=sala)
                dic = {
                    'sala': sala,
                    'insumos': ins
                }
                arreglo_salas += [dic]

            return render(request, self.success_url, context={
                'salas_disponibles': arreglo_salas,
                'cantidad_personas': cantidad,
                'insumos': insumos})


class ReservaCreateView(CreateView):
    template_name = 'reservaciones/reserva_exitosa.html'

    def post(self, request, *args, **kwargs):
        sala = request.POST.get('sala', None)
        horario_disponibilidad = request.POST.get('horario_disponibilidad', None)
        cantidad_personas = request.POST.get('cantidad_personas', None)
        insumos = request.POST.get('insumos', None)

        hora_termino = datetime.strptime(horario_disponibilidad, '%H:%M') + timedelta(hours=1)

        if sala:
            sala_instance = Sala.objects.get(id=sala)
            instance = Reservacion.objects.create(
                fecha=datetime.now(), hora_inicio=horario_disponibilidad,
                hora_termino=hora_termino.time(),
                cantidad_personas=cantidad_personas, sala=sala_instance, user=request.user,
                estatus=2
            )

            for insumo in insumos:
                insumo_instance = Insumo.objects.get(id=insumo)
                InsumoReservacion.objects.create(insumo=insumo_instance, reservacion=instance)

        return render(request, self.template_name, context={'mensaje': 'Sala reservada exitosamente!'})

salas/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title> HCMFront </title>
</head>
<body>
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">
            SALAS
          </a>
            {% if user.is_authenticated %}
              <p class="navbar-text">Hola {{ user.username }}!</p>
              <a href="{% url 'logout' %}" class="btn btn-default navbar-btn">logout</a>
            {% endif %}
        </div>

      </div>
    </nav>

  </header>
  <hr>
      <main>
      <div class="container well">
        {% block title %}{% endblock %}
      </div>
        {% block content %}{% endblock %}
      </main>
  <hr>
</body>
</html>

salas/templates/home.html
{% extends 'base.html' %}

{% block title %} Admin {% endblock %}

{% block content %}
    <p>
        <a href="{% url "salas:list" %}">Administrar Salas</a>
    </p>

    <p>
        <a href="{% url "reservaciones:list" %}">Administrar Reservaciones</a>
    </p>

{% endblock %}

salas/templates/index.html
{% extends "admin/base_site.html" %}

<div class="row">
    <div class="container col-md-6">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send message" />
        </form>
    </div>
</div>

salas/templates/login.html
{% extends 'base.html' %}
{# Load the tag library #}
{% load bootstrap3 %}

{% block title %} <h2> Inicia sesión </h2>{% endblock %}
{% block content %}
  <div class="container well">
    <h2>Login</h2>
    <form method="post">
        {% bootstrap_form form %}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>

{% endblock %}

salas/templates/reservaciones/reserva.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %} <h2> Formulario de Reserva </h2>{% endblock %}

{% block content %}
    <div class="container well">
        <form method="post">
            {% bootstrap_form form %}
        {% csrf_token %}
        <input type="submit" value="Submit" class="btn btn-primary"/>
    </form>
    </div>

{% endblock %}

salas/templates/reservaciones/reserva_exitosa.html
{% extends 'base.html' %}

{% block title %}
    <h2> Resultado </h2>
{% endblock %}

{% block content %}
    <div class="container well">
        <p>
        {{ mensaje }}
    </p>
    <p>
        <a href="{% url "reservaciones:reserva" %}" class="btn">Regresar</a>
    </p>
    </div>

{% endblock %}

salas/templates/reservaciones/salas_disponibles.html
{% extends 'base.html' %}

{% block title %}
    <h2> Resultados de búsqueda </h2>
    <small> <a href="{% url "reservaciones:reserva" %}">regresar</a></small>
{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-hover">
            <thead>
                <th>Nombre de la sala</th>
                <th>Horarios disponibles</th>
                <th>Capacidad</th>
                <th>Insumos disponibles</th>
                <th>Arrendar</th>
            </thead>
            <tbody>
             {% for sala in salas_disponibles %}
                <tr>
                    <td>{{ sala.sala.nombre }}</td>
                    <td>{{ sala.sala.horario_disponibilidad }}</td>
                    <td>{{ sala.sala.capacidad }}</td>
                    <td>{% for insumo in sala.insumos %}
                                {{ insumo }},
                             {% endfor %}
                    </td>
                    <td>
                        <form method="post" action="{% url "reservaciones:crearReserva" %}">
                            {% csrf_token %}
                            <input type="hidden" name="sala" value={{ sala.sala.id }} />
                            <input type="hidden" name="horario_disponibilidad" value={{ sala.sala.horario_disponibilidad }} />
                            <input type="hidden" name="cantidad_personas" value={{ cantidad_personas }} />
                            <input type="hidden" name="insumos" value={{ insumos }} />
                            <input type="submit" value="Arrendar" class="btn btn-success"/>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{#    <ul>#}
{#        {% for sala in salas_disponibles %}#}
{##}
{#            <li>#}
{#                <p>{{ sala.sala.nombre }}</p>#}
{##}
{#                <p>#}
{#                    Horario Disponibilidad: {{ sala.sala.horario_disponibilidad }} |#}
{#                    Capacidad: {{ sala.sala.capacidad }} |#}
{#                    Insumos: {% for insumo in sala.insumos %}#}
{#                                {{ insumo }},#}
{##}
{#                             {% endfor %}#}
{#                    <form method="post" action="{% url "reservaciones:crearReserva" %}">#}
{#                        {% csrf_token %}#}
{#                        <input type="hidden" name="sala" value={{ sala.sala.id }} />#}
{#                        <input type="hidden" name="horario_disponibilidad" value={{ sala.sala.horario_disponibilidad }} />#}
{#                        <input type="hidden" name="cantidad_personas" value={{ cantidad_personas }} />#}
{#                        <input type="hidden" name="insumos" value={{ insumos }} />#}
{#                        <input type="submit" value="Arrendar" />#}
{#                    </form>#}
{#                </p>#}
{##}
{##}
{#            </li>#}
{#        {% endfor %}#}
{#    </ul>#}
{% endblock %}